### ISSUE TITLE
App doesn't start on android emulator

### ISSUE THREAD

**Issue by Ly-sg** [jepiqueau/ionic-sqlite-typeorm-app#1]
Hello,
I tried to start the app on android emulator running the following command : 
`ionic cap run android --livereload`
I can view and interact with the application on chrome browser
It appears on the android emulator but when i launch it it just displays : 
Webpage is not available 
![image](https://github.com/jepiqueau/ionic-sqlite-typeorm-app/assets/61589599/d5dec193-188d-476d-bc74-37a8dd4ea7df)

Is it trying to run the web version on android ?

**Comment by jepiqueau** [comment]
@Ly-sg can you share your package.json file and part of the code where you set sqlite plugin

**Comment by Ly-sg** [comment]
@jepiqueau I'm using this repo's code, didn't change anything. I just tried to run it so that i can test it on an android emulator but it didn't work. Just checked the package.json it's identical to the repo's one

**Comment by jepiqueau** [comment]
@Ly-sg happy to know that it works. Can you please close the issue
