### ISSUE TITLE
Any chance to get an update ?

### ISSUE THREAD

**Issue by HijackHornet** [jepiqueau/ionic-sqlite-typeorm-app#3]
Do you plan in updating this template ? I tried and merge it with the non TypeORM which you updated but i failed to do so

**Comment by jepiqueau** [comment]
@HijackHornet do you want to use angular with modules or with components?

**Comment by jepiqueau** [comment]
@HijackHornet  Updated

**Comment by HijackHornet** [comment]
Oh thanks that was fast !!! 
You're the best :)
